#!/bin/sh
### BEGIN INIT INFO
# Provides:          resizepart_once
# Required-Start:
# Required-Stop:
# X-Start-Before:    resize2fs_once
# Default-Start: 2 3 4 5 S
# Default-Stop:
# Short-Description: Resize the root partition
# Description:
### END INIT INFO

. /lib/lsb/init-functions

#
# this is taken over from raspi-config script
#

case "$1" in
  start)

  log_daemon_msg "Expanding data partition to use full SD card capacity"

  # Get the starting offset of the root partition
  PART_START=$(parted /dev/mmcblk0 -ms unit s p | grep "^2" | cut -f 2 -d:)
  [ "$PART_START" ] || return 1
  # Return value will likely be error for fdisk as it fails to reload the 
  # partition table because the root fs is mounted
  fdisk /dev/mmcblk0 <<EOF
p
d
2
n
p
2
$PART_START

p
w
EOF

    rm /etc/init.d/resizepart_once &&
    update-rc.d resizepart_once remove &&
    log_end_msg $?
	echo "1" > /proc/sys/kernel/sysrq
	shutdown -r now && sync && echo "b" > /proc/sysrq-trigger
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac